
server:
  port: 8081

spring:
  application:
    name: redisTest
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      database: User


singleServerConfig:
  address: redis://127.0.0.1:6379
  password:
  database: 0





